export const projects = [
  {
    title: 'Message Wall Flask_App SQL',
    description: "Message wall style application that enables users to post, like, and delete messages. Login and registration with Bcrypt password encryption. Link to code source, and video demo below.",
      image: '/images/1.png',
      tags: ['Python', 'Flask', 'HTML', 'SQL', 'Bootstrap'],
    source: 'https://github.com/LimitlessUR/message_wall/tree/main/message_wall',
    visit: 'https://github.com/LimitlessUR/message_wall/tree/main/message_wall',
    id: 0,
  },
  {
    title: 'Live React Google Map Restuarant API',
    description:"This app enables our user to search any location and get resturants, attractions, and hotels in that area. It also includes detailed information cards to give our user as much information as possible about each establishment",
    image: '/images/7.png',
    tags: ['ReactJS', 'APIs', 'CSS', 'Visit via Source button'],
    source: 'https://dev8867.d39nqmjb3agqf8.amplifyapp.com',
    visit: 'https://github.com/LimitlessUR/Google_API_React',
    id: 1,
  },
  {
    title: 'Live React Exercise App APIs',
    description: "Given my experience in the fitness industry, this app was a lot of fun to program. Here, our user can search through the exercisedb API for over 1300 different exercises to add to thier routine. Try it out yourself",
    image: '/images/5.png',
    tags: ['Reactjs', 'API', 'CSS', 'Visit via Source button'],
    source: 'https://dev5303.d2s0x0njky1gl5.amplifyapp.com/',
    visit: 'https://github.com/LimitlessUR/ReactJS_Exercise_App_APIs',
    id: 3,
  },
  {
    title: 'Space Invaders',
    description: "The most fun one could have building a project! Building this blast from the past game with Python module 'Pygame' was a great lesson in Object Oriented Programming",
    image: '/images/4.jpg',
    tags: ['Python', 'Pygame'],
    source: 'https://github.com/LimitlessUR/Python_SpaceShooter',
    visit: 'https://github.com/LimitlessUR/Python_SpaceShooter',
    id: 3,
  },
  {
    title: 'Live React UI/UX Restuarant Website',
    description:"During this project I was introduced to the fundementals of UI/UX design, React file and folder structure for a highly aesthetic website, and how to form media queries for satisfactory responsiveness covering almost all devices ",
    image: '/images/6.png',
    tags: ['ReactJS', 'UI/UX', 'CSS', 'Visit via Source button'],
    source: 'https://master.d1qddam9popti2.amplifyapp.com',
    visit: 'https://github.com/LimitlessUR/Restaurant_UI-UX_Website',
    id: 1,
  },
  
  {
    title: 'Next.js Real Estate API App ',
    description:"This React Real Estate App allows our user to search and filter real estate data via the bayut API. Our user can choose to rent or buy and then use our filter feature to further customize their search",
    image: '/images/8.png',
    tags: ['ReactJS', 'next.js', 'CSS', 'APIs' ],
    source: 'https://github.com/LimitlessUR/Real_Estate_nextjsAPI',
    visit: 'https://github.com/LimitlessUR/Real_Estate_nextjsAPI',
    id: 1,
  },
  
  {
    title: 'Live React Todo List',
    description: "Here we have a React Todo list application that enables our user to add, edit and delete from their todo list. Our user can now plan their day with ease, and effeciency.",
      image: '/images/9.png',
      tags: ['React', 'Javascript', 'CSS', 'Try it out via Source Link'],
    source: 'https://dev7712.d3mxkjcetox33p.amplifyapp.com',
    visit: 'https://github.com/LimitlessUR/React-Todo-app',
    id: 2,
  },
  
  {
    title: 'Live React AI Website',
    description:"During completetion of this project I was introduced to React functional components and their reusability, React file and folder structure, Fundamentals of the CSS BEM Model, and other react fundamentals.",
    image: '/images/2.png',
    tags: ['React', 'UI/UX', 'CSS', 'Visit via Source button' ],
    source: 'https://dev1734.d2m9mq0vf8kq5e.amplifyapp.com',
    visit: 'https://github.com/LimitlessUR/React_AI_Website',
    id: 1,
  },
  {
    title: 'Currently working on the MERN Stack, and Python Pygame Platformer Projects',
    description: "So many fun projects, so little time! Check out my other projects throught the Code link below",
    image: '/images/codepic.jpg',
    tags: ['Python', 'ReactJS', 'Data Structure and Algorithms'],
    source: 'https://github.com/LimitlessUR',
    visit: 'https://github.com/LimitlessUR',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Worked as Metabolic Tech Specialist at Lifetime Fitness', },
  { year: 2020, text: 'Started as Ecommerce supervisor at Wholefoods', },
  { year: 2021, text: 'Began coding journey with Coding Dojo', },
  { year: 2022, text: 'Actively pursuing a career in Software Development and a deeper understanding of the coding world', },
];